VHDL_COMPILER=vcom

LIBRARY_PATH=./work
SYNTHESIS_ANALYSIS=analyze.tcl

VHDL_COMPILER=vcom
VHDL_COMPILER_OPT=-work $(LIBRARY_PATH) -2002 -bindAtCompile -check_synthesis

DIRECTORY_MISC=./0_MISC
DIRECTORY_FETCH=./1_FETCH
