
add wave -color green -label R0  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(0)/R0_REGISTER/REG/REG_data_out
add wave -color green -label R1  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(1)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R2  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(2)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R3  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(3)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R4  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(4)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R5  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(5)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R6  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(6)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R7  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(7)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R8  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(8)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R9  -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(9)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R10 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(10)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R11 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(11)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R12 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(12)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R13 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(13)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R14 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(14)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R15 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(15)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R16 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(16)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R17 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(17)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R18 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(18)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R19 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(19)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R20 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(20)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R21 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(21)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R22 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(22)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R23 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(23)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R24 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(24)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R25 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(25)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R26 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(26)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R27 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(27)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R28 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(28)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R29 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(29)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R30 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(30)/OTHER_REGISTERS/REG/REG_data_out
add wave -color green -label R31 -radix HEX sim:/tb_dlx/UUT/core_inst/ID/REGISTER_FILE/REGISTER_GEN(31)/OTHER_REGISTERS/REG/REG_data_out
